<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Suppress rules that don't apply cleanly to this domain model layer. -->
    <NoWarn>CA1034;CA1710;CA1000;CA2225;CA1716</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sovrant.Runtime\Sovrant.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5" />
  </ItemGroup>


</Project>
