<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Sovrant.Api\Sovrant.Api.csproj" />
    <ProjectReference Include="..\Sovrant.Runtime\Sovrant.Runtime.csproj" />
    <ProjectReference Include="..\Sovrant.Tools\Sovrant.Tools.csproj" />
    <ProjectReference Include="..\Sovrant.Commands\Sovrant.Commands.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>sovrant</AssemblyName>
    <!-- Console EXE entry point — suppress ConfigureAwait warning (CA2007) -->
    <NoWarn>CA2007</NoWarn>
  </PropertyGroup>

</Project>
