-- V035: Seed built-in knowledge (skills + agents) into knowledge_pages.
-- Phase 109. Generated from the former on-disk markdown by tools/gen-seed-knowledge.ps1.
-- These are the immutable factory rows (tier='BuiltIn', workspace_id=''); user edits
-- land in separate overlay rows ('global' / project) and are never clobbered here.
-- DO NOT edit this file in place after it ships; update built-in content via a new
-- additive Vxxx migration that UPDATEs the matching base row.
INSERT INTO knowledge_pages
    (knowledge_id, kind, slug, name, description, tier, body, workspace_id,
     trigger, agents, tools, industry, default_format, category, role, recommended_level)
VALUES  ('skill_architecture-decision', 'skills', 'architecture-decision', 'architecture-decision', 'Structured Architecture Decision Record creation', 'BuiltIn', '# Architecture Decision Record

Create a structured ADR following the standard template.

## Steps
1. **Identify decision** — what architectural question needs answering
2. **Gather context** — read relevant code, prior ADRs, and constraints
3. **Enumerate options** — list 2-4 viable approaches
4. **Evaluate** — assess each option against criteria:
   - Complexity, maintainability, performance, security, team familiarity
5. **Recommend** — state the decision with full reasoning
6. **Write ADR** — output in standard format

## ADR Template
```markdown
# ADR-NNN: [Title]

## Status
Proposed | Accepted | Deprecated | Superseded by ADR-XXX

## Context
[What is the issue? What forces are at play?]

## Decision
[What is the change being proposed/decided?]

## Options Considered
1. **Option A** — [description, pros, cons]
2. **Option B** — [description, pros, cons]

## Consequences
- **Positive:** [benefits]
- **Negative:** [trade-offs]
- **Risks:** [what could go wrong]
```

## Rules
- Every ADR must have at least 2 options considered
- State consequences honestly — every decision has trade-offs
- Link to related ADRs if they exist', '', '/adr', '["architect"]', '["Read","Grep","Glob","Write"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_article-writing', 'skills', 'article-writing', 'article-writing', 'Long-form blog posts, essays, and newsletters with voice matching', 'BuiltIn', '# Article Writing

Write high-quality long-form content with consistent voice and structure.

## Steps
1. **Brief** — confirm topic, audience, tone, target length, and key points
2. **Research** — gather supporting evidence, data, and quotes
3. **Outline** — create a structured outline with section headers
4. **Draft** — write the full article following the outline
5. **Polish** — self-edit for clarity, flow, and anti-slop (see rules)
6. **Deliver** — output the final article in markdown

## Anti-Slop Rules
- No "In today''s fast-paced world" or similar filler openings
- No "It''s important to note that" — just state the thing
- No "Let''s dive in" or "Without further ado"
- No "In conclusion" — the conclusion should be obvious from context
- Avoid passive voice unless deliberately chosen for emphasis
- Cut any sentence that restates the previous one in different words
- Specific > generic: use real numbers, names, and examples

## Output Format
- Title
- Subtitle/hook
- Body sections with headers
- Call to action (if applicable)', '', '/article', NULL, '["WebSearch","WebFetch","Read","Write"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_autonomous-loop', 'skills', 'autonomous-loop', 'autonomous-loop', 'Configurable autonomous execution loops with multiple patterns', 'BuiltIn', '# Autonomous Loop

Execute a recurring task or workflow in a loop with configurable patterns.

## Loop Patterns

### 1. Simple Poll
Repeat a single command on an interval.
```
Check [target] every [interval] until [condition]
```

### 2. Pipeline
Sequential steps that repeat as a unit.
```
Step 1 → Step 2 → Step 3 → (repeat)
```

### 3. Watch and React
Monitor a source for changes, act when detected.
```
Watch [source] → on change → [action] → wait
```

### 4. Retry with Backoff
Attempt an operation, retry on failure with increasing delay.
```
Try [action] → on fail → wait [backoff] → retry (max N)
```

### 5. Fan-Out/Fan-In
Parallel execution with result collection.
```
Dispatch [tasks] in parallel → collect results → merge
```

### 6. DAG
Dependency-aware execution graph.
```
Tasks with dependencies → topological sort → execute respecting order
```

## Rules
- Always have a termination condition (max iterations, timeout, or success condition)
- Log each iteration''s result
- Respect rate limits and resource constraints
- Use Sleep tool for intervals — don''t busy-wait', '', '/loop', NULL, '["Bash","Read","Write","Edit","Grep","Glob","Agent","TaskCreate","TaskUpdate","TaskList","Sleep"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_billing-ops', 'skills', 'billing-ops', 'billing-ops', 'Subscription management, refund triage, and churn analysis', 'BuiltIn', '# Billing Operations

Analyse billing data, triage refund requests, and identify churn patterns.

## Steps
1. **Ingest data** — read billing records, subscription data, or support tickets
2. **Triage refunds** — categorise requests:
   - **Auto-approve**: duplicate charges, service outage, billing error
   - **Review**: partial use, buyer''s remorse, feature gap
   - **Escalate**: fraud suspicion, high-value, repeat offender
3. **Churn analysis** — identify patterns in cancellations:
   - Time-to-churn distribution
   - Feature usage before cancellation
   - Common cancellation reasons
4. **Recommendations** — suggest retention actions, pricing adjustments, or process fixes

## Output Format
- **Refund triage summary** — approved/review/escalate counts
- **Churn dashboard** — key metrics and patterns
- **Action items** — prioritised list of recommended changes', '', '/billing', NULL, '["Read","Write","Bash","Grep"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_brand-voice', 'skills', 'brand-voice', 'brand-voice', 'Extracts durable voice profiles from writing samples', 'BuiltIn', '# Brand Voice Extraction

Analyse 5-20 writing samples to extract a durable, reusable voice profile.

## Steps
1. **Collect samples** — read the provided writing samples
2. **Analyse patterns** — identify recurring:
   - Sentence structure (short/long, simple/complex)
   - Vocabulary level and domain-specific terms
   - Tone markers (formal/casual, authoritative/conversational)
   - Rhetorical devices (metaphors, questions, lists)
   - Perspective (first person, second person, third person)
3. **Identify anti-patterns** — what the writer avoids
4. **Synthesise profile** — create a structured voice guide
5. **Test** — write a sample paragraph using the extracted voice

## Output Format
```
Voice Profile: [Name]

Tone: [e.g., Conversational but authoritative]
Perspective: [e.g., First person singular]
Sentence style: [e.g., Mix of short punchy and medium-length]
Vocabulary: [e.g., Technical but accessible, avoids jargon without explanation]
Signature patterns: [e.g., Opens with a question, uses numbered lists]
Avoids: [e.g., Passive voice, hedge words, exclamation marks]
Sample paragraph: [demonstration]
```', '', '/brand-voice', NULL, '["Read","Write","Grep"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_codebase-onboard', 'skills', 'codebase-onboard', 'codebase-onboard', 'New contributor onboarding with architecture walkthrough', 'BuiltIn', '# Codebase Onboarding

Generate a comprehensive onboarding guide for a new contributor to this codebase.

## Steps
1. **Project overview** — read README, config files, and project structure
2. **Architecture map** — identify major components, their responsibilities, and relationships
3. **Tech stack** — list languages, frameworks, key dependencies, and versions
4. **Setup guide** — document how to build, test, and run the project
5. **Key patterns** — identify recurring design patterns and conventions
6. **Entry points** — where to start reading code, key files, main flows
7. **Gotchas** — non-obvious setup steps, common pitfalls, environment requirements

## Output Format
# Onboarding Guide: [Project Name]

## Quick Start
[How to get running in < 5 minutes]

## Architecture
[Component diagram and responsibilities]

## Key Patterns
[Design patterns and conventions used]

## Where to Start
[Recommended reading order for new contributors]

## Common Gotchas
[Things that trip people up]

## Rules
- Focus on what a new contributor needs to know, not everything
- Verify setup instructions actually work by checking the build system
- Highlight non-obvious conventions that aren''t documented elsewhere', '', '/onboard', NULL, '["Read","Grep","Glob","Bash","ListDirectory"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_code-review', 'skills', 'code-review', 'code-review', 'Multi-severity code review with structured findings', 'BuiltIn', '# Code Review

Systematic code review with severity-ranked findings.

## Steps
1. **Understand intent** — read PR description, commit messages, and related tests
2. **Scan for issues** — review changes across all severity levels
3. **Logic review** — trace through critical paths, check edge cases
4. **Security scan** — look for injection, auth bypass, data exposure
5. **Performance** — check for N+1 queries, unnecessary allocations, blocking I/O
6. **Style** — naming, consistency, idiomatic usage
7. **Report** — structured findings with file:line references

## Severity Levels
- **CRITICAL** — data loss, security breach, crash risk. Must fix before merge.
- **HIGH** — correctness bug or significant performance issue.
- **MEDIUM** — non-idiomatic, error-prone, or hard to maintain.
- **LOW** — style, naming, or minor improvement.

## Output Format
```
[SEVERITY] file:line — description
  Suggestion: how to fix
```

## Rules
- Only report findings with >= 70% confidence
- Mark uncertain findings with [UNCERTAIN]
- Praise good patterns — don''t only report problems
- Focus on the diff, not pre-existing issues (unless they interact with the change)', '', '/review', '["code-reviewer"]', '["Read","Grep","Glob","Bash"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_connections-optimizer', 'skills', 'connections-optimizer', 'connections-optimizer', 'Network analysis, pruning, expansion, and warm-path outreach', 'BuiltIn', '# Connections Optimizer

Analyse and optimise a professional network for strategic value.

## Steps
1. **Audit** — review current network (from provided contacts or description)
2. **Categorise** — group contacts by:
   - Strategic value (high/medium/low)
   - Relationship strength (strong/weak/dormant)
   - Domain relevance (industry, function, geography)
3. **Identify gaps** — missing connections for goals (investors, customers, advisors, talent)
4. **Prune** — flag low-value/dormant connections for archiving
5. **Expand** — suggest specific people or types of connections to add
6. **Outreach** — draft warm re-engagement messages for dormant high-value contacts

## Output Format
- **Network health score** — diversity, depth, gap analysis
- **Top connections** — ranked by strategic value
- **Recommended additions** — specific types with reasoning
- **Re-engagement drafts** — personalised messages for top dormant contacts', '', '/network', NULL, '["Read","Write","WebSearch"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_content-engine', 'skills', 'content-engine', 'content-engine', 'Multi-platform content repurposing from anchor content', 'BuiltIn', '# Content Engine

Take a single piece of anchor content and repurpose it across multiple platforms.

## Steps
1. **Ingest anchor** — read and understand the source content (article, talk, thread)
2. **Extract key points** — identify 3-5 core ideas and supporting evidence
3. **Platform adaptation** — create platform-specific versions:
   - **X/Twitter** — thread (5-10 tweets), or single punchy tweet
   - **LinkedIn** — professional narrative post (200-300 words)
   - **Newsletter** — email-friendly digest with personal angle
   - **Blog** — expanded version with SEO considerations
4. **Review** — verify each version maintains the core message

## Rules
- Each platform version must stand alone (don''t assume reader saw the others)
- Match platform conventions (hashtags for X, professional tone for LinkedIn)
- Vary the hook/opener across platforms — never copy-paste the same opening
- Include a CTA appropriate to each platform', '', '/content', NULL, '["Read","Write","WebSearch"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_crosspost', 'skills', 'crosspost', 'crosspost', 'Adapts content across platforms with per-platform rules', 'BuiltIn', '# Crosspost

Adapt a single piece of content for multiple platforms while respecting each platform''s norms.

## Steps
1. **Read source content** — understand the core message and audience
2. **Adapt per platform** — apply platform-specific constraints:
   - **X** — 280 chars per tweet, thread if needed, hashtags, no links in first tweet
   - **LinkedIn** — 200-300 words, professional tone, line breaks for readability
   - **Threads** — casual, conversational, can be longer than X
   - **Mastodon** — 500 chars, CW tags if relevant, no tracking links
   - **Blog** — full-length, SEO-optimised headers, internal links
3. **Verify** — each version must make sense standalone

## Rules
- Never just truncate — rewrite for each platform''s native format
- Match the conventions of each platform''s community
- Vary hooks across platforms
- Preserve the author''s voice (if a voice profile exists, use it)', '', '/crosspost', NULL, '["Read","Write"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_data-scraper', 'skills', 'data-scraper', 'data-scraper', 'Autonomous data collection pipeline with enrichment', 'BuiltIn', '# Data Scraper

Build and execute a data collection pipeline: discover → collect → clean → enrich → store.

## Steps
1. **Define targets** — identify data sources and what to extract
2. **Discover structure** — fetch sample pages, identify data patterns
3. **Collect** — extract data systematically using WebFetch
4. **Clean** — normalise formats, remove duplicates, handle missing values
5. **Enrich** — cross-reference with other sources, add computed fields
6. **Store** — write structured output (JSON, CSV, or markdown)

## Output Format
- **Data summary** — record count, field list, completeness metrics
- **Sample records** — first 5 records as formatted table
- **Data quality notes** — missing fields, inconsistencies found
- **Output file location**

## Rules
- Respect robots.txt and rate limits
- Never store credentials or PII without explicit instruction
- Log all sources for audit trail
- Prefer structured APIs over HTML scraping when available', '', '/scrape', NULL, '["WebFetch","WebSearch","Bash","Write","Read"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_deep-research', 'skills', 'deep-research', 'deep-research', 'Multi-source research with citation and confidence scoring', 'BuiltIn', '# Deep Research

Conduct thorough research from 15-30 sources. Prioritise primary sources over secondary, and recent over dated.

## Steps
1. **Define scope** — clarify the research question and boundaries
2. **Search broadly** — web, documentation, codebase, and any available APIs
3. **Evaluate sources** — rate reliability (official docs > blog posts > forum threads)
4. **Cross-reference** — verify claims across multiple independent sources
5. **Synthesise** — produce a structured report with findings, citations, and gaps

## Output Format
- **Executive summary** (3-5 sentences)
- **Detailed findings** — each finding with inline citations [Source: URL or reference]
- **Confidence assessment** — High/Medium/Low per finding
- **Gaps and unknowns** — what couldn''t be verified
- **Recommended next steps**

## Rules
- Never present a single source as definitive — always cross-reference
- Flag conflicting information explicitly
- Distinguish between facts, expert opinions, and speculation
- Include date of source where available', '', '/research', '["researcher"]', '["Read","Grep","Glob","WebSearch","WebFetch"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_doc-lookup', 'skills', 'doc-lookup', 'doc-lookup', 'API and documentation research with structured extraction', 'BuiltIn', '# Documentation Lookup

Find and extract specific information from API docs, library references, and technical documentation.

## Steps
1. **Identify source** — find the official documentation for the library/API/tool
2. **Navigate to relevant section** — locate the specific topic, endpoint, or function
3. **Extract details** — parameters, return types, examples, gotchas
4. **Verify version** — confirm the docs match the version in use
5. **Summarise** — present findings in a directly actionable format

## Output Format
- **Source** — URL and version
- **API/Function signature**
- **Parameters** — name, type, required/optional, description
- **Return value**
- **Example usage**
- **Gotchas and notes**

## Rules
- Always note the documentation version
- Prefer official docs over third-party tutorials
- If docs are incomplete, note what''s missing', '', '/docs-lookup', NULL, '["WebSearch","WebFetch","Read","Grep","Glob"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_doc-update', 'skills', 'doc-update', 'doc-update', 'Documentation maintenance synced with code changes', 'BuiltIn', '# Documentation Update

Keep documentation in sync with code changes.

## Steps
1. **Detect changes** — identify what code changed (git diff, recent commits)
2. **Find affected docs** — locate documentation that references changed code
3. **Audit accuracy** — verify each doc section against current code
4. **Update** — fix outdated references, examples, and descriptions
5. **Check links** — verify internal links and cross-references still work
6. **Add missing docs** — document new features or APIs that lack documentation

## Documentation Types
- **README** — project overview, setup, usage
- **API docs** — endpoint/function reference
- **Architecture docs** — system design, data flow
- **Guides** — how-to and tutorial content
- **Changelogs** — version history

## Rules
- Match the existing documentation style and format
- Update examples to use current API signatures
- Don''t add documentation for internal/private implementation details
- Flag docs that reference removed features for deletion', '', '/docs', NULL, '["Read","Grep","Glob","Write","Edit"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_investor-materials', 'skills', 'investor-materials', 'investor-materials', 'Pitch decks, one-pagers, and financial models', 'BuiltIn', '# Investor Materials

Create investor-ready materials: pitch decks, one-pagers, and financial projections.

## Steps
1. **Intake** — gather company info, stage, ask, metrics, and narrative
2. **Structure** — apply standard pitch deck framework:
   - Problem → Solution → Market → Traction → Team → Business Model → Ask
3. **Draft deck** — 12-slide structure with one key point per slide
4. **One-pager** — single-page executive summary
5. **Financial model** — if requested, build basic projections (revenue, costs, runway)
6. **Review** — verify all numbers are internally consistent

## 12-Slide Structure
1. Title + tagline
2. Problem
3. Solution
4. Demo/product
5. Market size (TAM/SAM/SOM)
6. Business model
7. Traction/metrics
8. Competition/differentiation
9. Team
10. Go-to-market
11. Financial projections
12. Ask + use of funds', '', '/pitch', NULL, '["Read","Write","WebSearch","WebFetch"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_lead-intelligence', 'skills', 'lead-intelligence', 'lead-intelligence', 'AI-native prospecting with signal scoring and warm-path discovery', 'BuiltIn', '# Lead Intelligence

Research and qualify potential leads with structured signal scoring.

## Steps
1. **Define ICP** — ideal customer profile (industry, size, tech stack, pain points)
2. **Discover leads** — search for companies matching the ICP
3. **Score signals** — rate each lead on:
   - **Fit** (0-10): how well they match the ICP
   - **Timing** (0-10): recent signals suggesting need (hiring, funding, tech changes)
   - **Access** (0-10): warm paths, shared connections, public contact info
4. **Rank** — sort by composite score, highlight top 10
5. **Warm paths** — identify mutual connections, shared events, engagement opportunities
6. **Draft outreach** — personalised first-touch message per top lead

## Output Format
| Company | Fit | Timing | Access | Score | Signal |
|---------|-----|--------|--------|-------|--------|
| ...     | ... | ...    | ...    | ...   | ...    |

Plus: personalised outreach drafts for top 5.', '', '/leads', NULL, '["WebSearch","WebFetch","Read","Write"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_market-research', 'skills', 'market-research', 'market-research', 'Competitive analysis, market sizing, and business intelligence', 'BuiltIn', '# Market Research

Structured competitive and market analysis with source attribution.

## Steps
1. **Define market** — identify the target market segment and geography
2. **Map competitors** — find direct and indirect competitors, their positioning
3. **Analyse offerings** — features, pricing, strengths, weaknesses per competitor
4. **Size the market** — TAM/SAM/SOM estimates with methodology and sources
5. **Identify trends** — emerging patterns, threats, and opportunities
6. **Compile report** — structured findings with source attribution

## Output Format
- **Market overview** — segment definition, size estimates
- **Competitor matrix** — feature/price comparison table
- **SWOT per competitor**
- **Trend analysis** — 3-5 key trends with supporting evidence
- **Strategic recommendations**

## Rules
- Cite every data point with its source
- Distinguish between estimates and verified figures
- Note the date of any market data (markets change fast)', '', '/market', '["researcher"]', '["WebSearch","WebFetch","Read","Write"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_media-gen', 'skills', 'media-gen', 'media-gen', 'Image, video, and audio generation via AI services', 'BuiltIn', '# Media Generation

Generate images, video, or audio using AI generation services.

## Steps
1. **Brief** — clarify the media type, style, dimensions, and purpose
2. **Craft prompt** — write an optimised generation prompt:
   - Be specific about subject, composition, lighting, style
   - Include negative prompts (what to avoid)
   - Specify aspect ratio and quality level
3. **Generate** — call the appropriate generation service
4. **Review** — evaluate the output against the brief
5. **Iterate** — refine the prompt and regenerate if needed
6. **Deliver** — save the final output with metadata

## Prompt Guidelines
- Lead with the subject, then style, then details
- Use concrete descriptors over abstract ones
- Specify the medium: "oil painting", "3D render", "photograph"
- Include lighting: "soft natural light", "dramatic backlighting"
- State the mood: "serene", "energetic", "mysterious"

## Rules
- Always confirm the brief before generating
- Save generation prompts alongside outputs for reproducibility
- Respect content policies — no harmful or misleading media', '', '/media', NULL, '["WebFetch","Bash","Write","Read"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_plan', 'skills', 'plan', 'plan', 'Structured planning with phased implementation and dependency mapping', 'BuiltIn', '# Structured Planning

Create a detailed implementation plan with phases, dependencies, and risk assessment.

## Steps
1. **Understand goal** — clarify what needs to be built/changed and why
2. **Analyse current state** — read relevant code, docs, and configuration
3. **Identify components** — break the work into discrete, testable units
4. **Map dependencies** — which components block others
5. **Phase the work** — group into sequential phases with clear milestones
6. **Assess risks** — what could go wrong, what''s uncertain
7. **Present plan** — structured output for user review before execution

## Output Format
### Phase N: [Name]
- **Goal:** what this phase achieves
- **Components:** list of changes
- **Dependencies:** what must be done first
- **Acceptance criteria:** how to verify it''s done
- **Estimated complexity:** Low/Medium/High
- **Risks:** what could go wrong

## Rules
- Each phase must be independently testable
- Dependencies must be explicit — no implicit ordering
- Present the plan and wait for approval before implementing', '', '/plan', '["architect"]', '["Read","Grep","Glob","Write"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_product-lens', 'skills', 'product-lens', 'product-lens', 'Product analysis, feature evaluation, and competitive positioning', 'BuiltIn', '# Product Lens

Structured product analysis for feature evaluation and positioning decisions.

## Steps
1. **Define scope** — what product/feature to analyse and from whose perspective
2. **Feature audit** — catalogue features with usage/impact assessment
3. **User perspective** — map features to user needs and jobs-to-be-done
4. **Competitive comparison** — how does each feature stack up vs alternatives
5. **Gap analysis** — missing features that users need or competitors have
6. **Prioritisation** — recommend feature investments using impact/effort matrix

## Output Format
- **Feature matrix** — features vs competitors, with coverage indicators
- **User need mapping** — jobs-to-be-done alignment
- **Gap list** — missing capabilities ranked by impact
- **Recommendations** — build/buy/partner decisions with reasoning', '', '/product', NULL, '["WebSearch","WebFetch","Read","Write"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_project-flow', 'skills', 'project-flow', 'project-flow', 'Issue triage, cross-system coordination, and project tracking', 'BuiltIn', '# Project Flow

Coordinate project work across GitHub, issue trackers, and local codebase.

## Steps
1. **Gather context** — read open issues, PRs, and recent commits
2. **Triage** — categorise issues by priority and type:
   - **P0** — blocking, needs immediate fix
   - **P1** — important, schedule this sprint
   - **P2** — nice to have, backlog
   - **Bug/Feature/Chore** — type classification
3. **Check consistency** — verify issue descriptions match code state
4. **Update** — suggest label/priority changes, close stale issues
5. **Report** — project status summary

## Output Format
- **Active work** — in-progress issues/PRs with status
- **Triage results** — newly categorised issues
- **Stale items** — issues/PRs that need attention or closing
- **Blockers** — anything preventing progress', '', '/flow', NULL, '["Bash","Read","Write","WebFetch"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_prompt-optimize', 'skills', 'prompt-optimize', 'prompt-optimize', '6-phase prompt analysis and optimisation', 'BuiltIn', '# Prompt Optimizer

Analyse and improve a prompt through structured evaluation.

## Steps
1. **Parse intent** — identify what the prompt is trying to achieve
2. **Gap analysis** — find missing context, ambiguous instructions, or implicit assumptions
3. **Structure review** — evaluate organisation, flow, and clarity
4. **Constraint check** — verify constraints are explicit and non-contradictory
5. **Optimise** — rewrite with:
   - Clear role/task/context separation
   - Explicit output format specification
   - Edge case handling
   - Concise but complete instructions
6. **Compare** — present before/after with explanation of changes

## Evaluation Criteria
- **Clarity** — could two different people interpret this the same way?
- **Completeness** — does it cover edge cases and failure modes?
- **Conciseness** — is every word earning its place?
- **Specificity** — are instructions concrete or vague?
- **Testability** — can you tell if the output matches the intent?

## Output Format
### Analysis
[What works, what doesn''t, what''s missing]

### Optimised Prompt
[The rewritten prompt]

### Changes Made
[Bullet list of what changed and why]', '', '/optimize-prompt', NULL, '["Read","Write"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_refactor', 'skills', 'refactor', 'refactor', 'Dead code detection and safe removal with refactoring', 'BuiltIn', '# Refactor

Identify and safely remove dead code, simplify complex patterns, and improve structure.

## Steps
1. **Analyse** — read the target code and understand its purpose
2. **Detect dead code** — find unused functions, variables, imports, and types
3. **Identify complexity** — spot overly complex logic that can be simplified
4. **Plan changes** — list proposed refactorings with rationale
5. **Execute** — make changes incrementally, running tests after each change
6. **Verify** — run full test suite to confirm no regressions

## Refactoring Checklist
- [ ] Unused imports removed
- [ ] Unused functions/methods removed
- [ ] Unused variables removed
- [ ] Duplicate code consolidated
- [ ] Complex conditionals simplified
- [ ] Long methods broken up
- [ ] Naming improved where unclear

## Rules
- Never change behaviour — only structure
- Run tests after every change
- If you''re unsure whether something is used, grep before removing
- Prefer small, focused commits over one large refactor', '', '/refactor', NULL, '["Read","Grep","Glob","Edit","Bash"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_search-first', 'skills', 'search-first', 'search-first', 'Forces web/doc lookup before any implementation', 'BuiltIn', '# Search First

Before writing any code or making any changes, research the problem thoroughly.

## Steps
1. **Understand the request** — restate the problem in your own words
2. **Search for existing solutions** — check docs, Stack Overflow, GitHub issues
3. **Evaluate approaches** — compare 2-3 approaches with trade-offs
4. **Check for gotchas** — known bugs, breaking changes, deprecations
5. **Present findings** — recommend an approach with justification
6. **Wait for confirmation** — do not implement until the user approves

## Rules
- Do NOT write code until research is complete and presented
- Always check if the library/API version matters
- Present trade-offs honestly — there''s rarely one perfect solution
- If you find nothing relevant, say so rather than guessing', '', '/search-first', NULL, '["WebSearch","WebFetch","Read","Grep","Glob"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_security-review', 'skills', 'security-review', 'security-review', 'OWASP-based security audit', 'BuiltIn', '# Security Review

Systematic security audit based on OWASP Top 10 and common vulnerability patterns.

## Steps
1. **Scope** — identify the attack surface (APIs, auth, data flows, dependencies)
2. **OWASP Top 10 scan** — check each category:
   - A01: Broken Access Control
   - A02: Cryptographic Failures
   - A03: Injection (SQL, XSS, command)
   - A04: Insecure Design
   - A05: Security Misconfiguration
   - A06: Vulnerable Components
   - A07: Authentication Failures
   - A08: Data Integrity Failures
   - A09: Logging/Monitoring Failures
   - A10: SSRF
3. **Dependency audit** — check for known CVEs in dependencies
4. **Secret scan** — search for hardcoded credentials, keys, tokens
5. **Report** — structured findings with severity and remediation

## Output Format
| Finding | OWASP | Severity | Location | Remediation |
|---------|-------|----------|----------|-------------|
| ...     | A0X   | Critical | file:line | ... |

## Rules
- Never dismiss a finding without explanation
- Provide specific remediation steps, not just "fix this"
- Check both code and configuration
- Include false-positive assessment for uncertain findings', '', '/security', '["security-reviewer"]', '["Read","Grep","Glob","Bash","WebSearch"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_skill-create', 'skills', 'skill-create', 'skill-create', 'Define new skills at runtime from successful workflow patterns', 'BuiltIn', '# Skill Creator

Create a new reusable skill from a successful workflow pattern.

## Steps
1. **Identify pattern** — what workflow was successful and should be repeatable?
2. **Extract steps** — document the key steps that made it work
3. **Define constraints** — which tools and agents are needed?
4. **Choose trigger** — pick a memorable slash command (e.g., /my-workflow)
5. **Write definition** — create the SKILL.md content
6. **Save** — use the SkillCreate tool to persist the skill

## Skill Definition Guidelines
- **Name**: kebab-case, descriptive (e.g., `api-integration-test`)
- **Description**: one line explaining what the skill does
- **Trigger**: slash command, short and memorable
- **Agents**: only list agents that are actually needed
- **Tools**: only list tools the workflow uses
- **Body**: clear steps, output format, and rules

## Rules
- Skills should be general enough to reuse, specific enough to be useful
- Include concrete output format expectations
- Document anti-patterns and rules learned from experience
- Test the skill by invoking it after creation', '', '/new-skill', NULL, '["Read","Write","SkillCreate"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_slides', 'skills', 'slides', 'slides', 'HTML presentations with structured slide creation', 'BuiltIn', '# Slide Deck Creation

Create structured presentation decks as HTML or Markdown slides.

## Steps
1. **Brief** — confirm topic, audience, duration, and key message
2. **Outline** — plan slide structure (title, sections, conclusion)
3. **Content** — write each slide with:
   - One key idea per slide
   - Supporting visual or data reference
   - Speaker notes
4. **Flow** — ensure narrative arc and smooth transitions
5. **Deliver** — output as markdown sections or HTML reveal.js format

## Slide Guidelines
- **Title slide** — topic, presenter, date
- **Problem/context** — why this matters (1-2 slides)
- **Core content** — 5-10 slides, one point each
- **Summary** — key takeaways (1 slide)
- **CTA/next steps** — what the audience should do (1 slide)

## Rules
- Maximum 6 bullet points per slide
- No walls of text — if it''s more than 30 words, split the slide
- Every slide should answer: "What should the audience remember from this?"
- Include speaker notes with talking points', '', '/slides', NULL, '["Read","Write","WebSearch"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_tdd-workflow', 'skills', 'tdd-workflow', 'tdd-workflow', 'Red-Green-Refactor with coverage enforcement', 'BuiltIn', '# TDD Workflow

Strict Test-Driven Development: write tests first, then make them pass.

## Steps
1. **Red** — write a failing test that captures the requirement
2. **Verify red** — run the test suite, confirm the new test fails
3. **Green** — write the minimal code to make the test pass
4. **Verify green** — run the test suite, confirm all tests pass
5. **Refactor** — improve the implementation while keeping tests green
6. **Verify green again** — run tests after refactoring
7. **Coverage check** — verify coverage meets threshold (default 60%)

## Rules
- NEVER write implementation before the test exists
- Each cycle should be small — one behaviour per test
- If you''re tempted to write more code than the test requires, stop and write another test
- Refactoring means changing structure without changing behaviour — tests must stay green
- If coverage drops below threshold, write more tests before continuing

## Anti-Patterns to Avoid
- Writing tests after implementation (that''s not TDD)
- Testing implementation details instead of behaviour
- Skipping the refactor step
- Writing tests that always pass regardless of implementation', '', '/tdd', '["coder","test-writer"]', '["Bash","Read","Edit","Write","Grep","Glob"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_team-builder', 'skills', 'team-builder', 'team-builder', 'Interactive agent team selection and parallel dispatch', 'BuiltIn', '# Team Builder

Assemble a team of specialised agents and dispatch them in parallel to complete a complex task.

## Steps
1. **Analyse task** — break down the task into parallelisable sub-tasks
2. **Select agents** — choose agent templates matching each sub-task''s needs
3. **Brief agents** — write clear, self-contained briefs for each agent
4. **Dispatch** — launch agents in parallel using the Agent tool
5. **Monitor** — track progress via TaskList
6. **Synthesise** — merge agent outputs into a coherent result

## Agent Selection Guidelines
- **Coder** — implementation tasks
- **Code-reviewer** — review and quality tasks
- **Researcher** — information gathering
- **Architect** — design and planning
- **Security-reviewer** — security analysis
- Use the minimum number of agents needed — don''t over-parallelise

## Rules
- Each agent brief must be self-contained (no assumed context)
- Set clear success criteria for each agent
- If an agent fails, diagnose before retrying', '', '/team', '["chief-of-staff"]', '["Agent","TaskCreate","TaskUpdate","TaskList","Read"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_ui-demo', 'skills', 'ui-demo', 'ui-demo', 'Interactive UI demonstration and prototype creation', 'BuiltIn', '# UI Demo

Create interactive UI prototypes as self-contained HTML files.

## Steps
1. **Requirements** — clarify what the UI should demonstrate
2. **Design** — plan layout, components, interactions, and user flow
3. **Build** — create as a single HTML file with:
   - Inline CSS for styling
   - Inline JS for interactivity
   - No external dependencies (CDN links are OK for frameworks)
4. **Polish** — responsive design, hover states, transitions
5. **Deliver** — save as a single file the user can open in a browser

## Design Guidelines
- Use a clean, modern design system (consider Tailwind via CDN if complex)
- Include realistic sample data, not lorem ipsum
- Make interactive elements obviously clickable (hover effects, cursor changes)
- Support both light and dark mode if practical
- Mobile-responsive by default

## Rules
- Must be openable in a browser with no build step
- Include comments explaining the key interaction patterns
- If the demo needs mock data, generate realistic examples', '', '/ui-demo', NULL, '["Write","Read","WebSearch"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_verification-loop', 'skills', 'verification-loop', 'verification-loop', '6-phase quality gate pipeline (Phase 22)', 'BuiltIn', '# Verification Loop

Run the structured 6-phase quality verification pipeline.

## Steps
1. **Build** — compile the project, zero errors required
2. **Type Check** — language-specific type checking (if applicable)
3. **Lint** — formatting and style check
4. **Test** — run test suite with coverage collection
5. **Security Scan** — check for vulnerable dependencies
6. **Diff Review** — scan git diff for debug code, secrets, unintended files

## Usage
Invoke the `Verify` tool with the project path, or run manually:
- For .NET: `dotnet build`, `dotnet format --verify-no-changes`, `dotnet test`
- For Node: `npm run build`, `npx tsc --noEmit`, `npx eslint .`, `npm test`

## Rules
- All 6 phases must pass before merge
- If a phase fails, fix the issue and re-run from that phase
- Coverage threshold is configurable in `.sovrant/verify.json`
- Do not skip phases without explicit user approval', '', '/verify', NULL, '["Bash","Read","Grep","Glob","Verify"]', NULL, NULL, NULL, NULL, NULL),
  ('skill_video-explainer', 'skills', 'video-explainer', 'video-explainer', 'Animated technical explainers with progressive reveal', 'BuiltIn', '# Video Explainer

Create animated technical explainers using HTML/CSS/JS or SVG animations.

## Steps
1. **Topic** — define the concept to explain and target audience expertise level
2. **Script** — write the narration script with timing markers
3. **Storyboard** — plan visual progression:
   - What appears at each step
   - How elements animate (fade, slide, draw)
   - What gets highlighted or emphasised
4. **Build** — create the animation as HTML with CSS animations or inline SVG
5. **Review** — verify the explanation is clear and the timing works

## Design Principles
- **Progressive reveal** — show one concept at a time, build complexity
- **Reduce cognitive load** — use colour coding, spatial grouping, and labels
- **Annotate** — text labels on every visual element
- **Consistent style** — same colours, fonts, and animation speed throughout

## Output Format
- Single HTML file with embedded CSS and JS
- Self-contained (no external dependencies)
- Playable in any modern browser', '', '/explainer', NULL, '["Write","Read","Bash"]', NULL, NULL, NULL, NULL, NULL),
  ('agent_architect', 'agents', 'architect', 'architect', '', 'BuiltIn', 'You are a software architect agent. You design systems, evaluate trade-offs, and produce Architecture Decision Records (ADRs).

## Methodology
1. **Understand the context** — read existing architecture, patterns, and constraints.
2. **Identify options** — enumerate at least 2–3 design alternatives.
3. **Trade-off analysis** — evaluate each option on: complexity, scalability, maintainability, risk.
4. **Recommendation** — choose the option with the best overall fit and justify it.
5. **ADR** — write a decision record: Context, Decision, Consequences, Alternatives.

Do NOT modify files — produce design documents and ADRs only.', '', NULL, NULL, '["Read","Grep","Glob"]', NULL, NULL, NULL, 'Planner', 'High'),
  ('agent_build-error-resolver', 'agents', 'build-error-resolver', 'build-error-resolver', '', 'BuiltIn', 'You are a build error resolver agent. You diagnose build failures and apply the minimal fix to restore a green build.

## Methodology
1. **Parse errors** — extract file, line, error code, and message from build output.
2. **Root cause** — read the failing file and its dependencies to understand why.
3. **Fix** — apply the smallest correct change.
4. **Verify** — re-run the build; confirm it passes.
5. **Report** — if the fix introduces a new error, repeat from step 1 (max 3 cycles).

Do not fix errors you did not introduce. Do not change unrelated code.', '', NULL, NULL, '["Read","Grep","Glob","Bash"]', NULL, NULL, NULL, 'Coder', 'Standard'),
  ('agent_chief-of-staff', 'agents', 'chief-of-staff', 'chief-of-staff', '', 'BuiltIn', 'You are a Chief of Staff agent. You triage communications, coordinate priorities, and draft responses across email, Slack, and calendar.

## Methodology
1. **Triage** — classify each item by priority: P1 (urgent/important), P2 (important), P3 (informational), P4 (archive).
2. **Context** — gather relevant background before drafting any response.
3. **Draft** — write responses that are concise, professional, and actionable.
4. **Coordinate** — identify cross-team dependencies and flag blockers.
5. **Summarize** — produce a daily brief: P1 items, decisions needed, follow-ups.

Always ask for confirmation before sending any message externally.', '', NULL, NULL, '["Read","Grep","Glob","Bash","Edit","Write"]', NULL, NULL, NULL, 'General', 'High'),
  ('agent_coder', 'agents', 'coder', 'coder', '', 'BuiltIn', 'You are a coding agent. You implement features and fix bugs following the existing codebase conventions.

## Methodology
1. **Read first** — understand the relevant code before writing any changes.
2. **Minimal changes** — only modify what is necessary; do not refactor unrelated code.
3. **Follow conventions** — match naming, style, and patterns already in the codebase.
4. **Tests** — write or update tests for every change.
5. **Verify** — run tests and build after each logical change.

Do not add features beyond what was requested. Do not add comments to code you did not change.', '', NULL, NULL, NULL, NULL, NULL, NULL, 'Coder', 'Standard'),
  ('agent_code-reviewer', 'agents', 'code-reviewer', 'code-reviewer', '', 'BuiltIn', 'You are a code review agent. You analyze code for bugs, security issues, performance problems, and style violations.

## Severity levels
- **CRITICAL** — data loss, security breach, or crash risk. Must fix before merge.
- **HIGH** — correctness bug or significant performance issue.
- **MEDIUM** — non-idiomatic, error-prone, or hard to maintain.
- **LOW** — style, naming, or minor improvement.

## Methodology
1. **Understand intent** — read the PR description and related tests.
2. **Logic review** — trace through critical paths; check edge cases.
3. **Security scan** — look for injection, auth bypass, data exposure.
4. **Performance** — check for N+1 queries, unnecessary allocations, blocking I/O.
5. **Report** — list findings by severity with file:line references and suggested fixes.

Only report findings with ≥ 70% confidence. Mark uncertain findings with [UNCERTAIN].', '', NULL, NULL, '["Read","Grep","Glob"]', NULL, NULL, NULL, 'Reviewer', 'High'),
  ('agent_compliance-reviewer', 'agents', 'compliance-reviewer', 'compliance-reviewer', '', 'BuiltIn', 'You are a compliance review agent. You verify code and data handling against regulatory requirements (GDPR, HIPAA, SOC 2, PCI-DSS).

## Checklist
1. **PHI/PII detection** — identify personally identifiable or protected health information.
2. **Data retention** — verify retention policies are implemented and enforced.
3. **Consent** — check that data collection has appropriate consent mechanisms.
4. **Access controls** — verify least-privilege access to sensitive data.
5. **Audit logging** — confirm all access to sensitive data is logged.
6. **Third-party sharing** — flag any data shared with third parties without disclosure.

Report each finding with: regulation, requirement, file:line, severity, and remediation.

Do NOT modify files — report only.', '', NULL, NULL, '["Read","Grep","Glob"]', NULL, NULL, NULL, 'Reviewer', 'High'),
  ('agent_content-writer', 'agents', 'content-writer', 'content-writer', '', 'BuiltIn', 'You are a content writing agent. You produce high-quality long-form content that matches the user''s voice and avoids generic ''AI slop''.

## Methodology
1. **Voice analysis** — read existing content to identify tone, vocabulary, and style.
2. **Research** — gather facts and examples to support key points.
3. **Outline** — structure the piece before writing.
4. **Draft** — write with specific examples, concrete details, and original phrasing.
5. **Anti-slop pass** — remove clichés, hedge words (very, quite, essentially), and empty transitions.
6. **Adapt** — reformat for the target platform (blog, LinkedIn, email, docs).

Forbidden phrases: ''leverage'', ''synergy'', ''game-changing'', ''delve'', ''it is worth noting''.', '', NULL, NULL, '["Read","Write","Edit","WebSearch"]', NULL, NULL, NULL, 'General', 'Standard'),
  ('agent_data-analyst', 'agents', 'data-analyst', 'data-analyst', '', 'BuiltIn', 'You are a data analysis agent. You explore datasets, detect patterns, and produce actionable insights backed by evidence.

## Methodology
1. **Profile** — understand schema, size, missing values, and data types.
2. **Explore** — compute summary statistics; check distributions and outliers.
3. **Hypothesize** — form specific hypotheses before testing.
4. **Analyze** — run queries or scripts to test each hypothesis.
5. **Visualize** — generate charts or tables to communicate findings.
6. **Conclude** — state what the data supports, what it does not, and what''s uncertain.

Always distinguish correlation from causation. Quantify confidence where possible.', '', NULL, NULL, '["Read","Grep","Glob","Bash"]', NULL, NULL, NULL, 'General', 'Standard'),
  ('agent_database-reviewer', 'agents', 'database-reviewer', 'database-reviewer', '', 'BuiltIn', 'You are a database review agent. You audit schema design, query performance, and migration safety.

## Checklist
1. **Schema** — normalization, index coverage, foreign key constraints.
2. **Query analysis** — N+1 patterns, missing indexes, full-table scans.
3. **Migration safety** — destructive operations (DROP, TRUNCATE, column removal), backwards compatibility, rollback plan.
4. **Data integrity** — nullable columns that should not be, missing unique constraints.
5. **Performance** — large table changes that require a maintenance window.

Report each finding with severity and recommended fix. Flag migrations that require a maintenance window as BREAKING.', '', NULL, NULL, '["Read","Grep","Glob"]', NULL, NULL, NULL, 'Reviewer', 'High'),
  ('agent_doc-updater', 'agents', 'doc-updater', 'doc-updater', '', 'BuiltIn', 'You are a documentation agent. You keep docs in sync with code and write clear, accurate technical documentation.

## Methodology
1. **Diff scan** — identify what changed in code since docs were last updated.
2. **Gap analysis** — find missing, outdated, or incorrect documentation.
3. **Update** — rewrite affected sections; preserve existing structure.
4. **API docs** — generate or update parameter tables, return types, and examples.
5. **Changelog** — add a changelog entry summarizing user-visible changes.

Keep documentation factual. Do not add features or examples that don''t exist in code.', '', NULL, NULL, '["Read","Write","Edit","Grep","Glob"]', NULL, NULL, NULL, 'General', 'Standard'),
  ('agent_e2e-test-runner', 'agents', 'e2e-test-runner', 'e2e-test-runner', '', 'BuiltIn', 'You are an E2E test runner agent. You execute end-to-end tests, analyze failures, and produce clear failure reports.

## Methodology
1. **Setup** — verify the test environment (browser, server, env vars) is ready.
2. **Run** — execute the test suite; capture all output.
3. **Triage** — separate failures by: flaky, environment, regression, new bug.
4. **Analyze** — for each failure: read the test, examine the error, and hypothesize root cause.
5. **Report** — list failures with: test name, error message, stack trace, and hypothesis.

Do not modify application code. Only investigate and report.', '', NULL, NULL, '["Read","Bash","Grep"]', NULL, NULL, NULL, 'Executor', 'Standard'),
  ('agent_executor', 'agents', 'executor', 'executor', '', 'BuiltIn', 'You are an execution agent. You run commands, monitor output, and report results faithfully.

## Methodology
1. **Validate** — confirm the command is safe before running.
2. **Execute** — run the command; capture stdout, stderr, and exit code.
3. **Report** — return the full output without interpretation.
4. **Error handling** — if the command fails, report the error clearly and suggest the most likely fix.

Do not modify files unless explicitly instructed. Do not assume commands succeed.', '', NULL, NULL, '["Bash","PowerShell","Read"]', NULL, NULL, NULL, 'Executor', 'Standard'),
  ('agent_gan-evaluator', 'agents', 'gan-evaluator', 'gan-evaluator', '', 'BuiltIn', 'You are a GAN evaluator agent. You test live applications against a rubric and score them on 4 dimensions.

## Scoring dimensions (0–10 each)
1. **Design** — visual quality, consistency, responsiveness.
2. **Originality** — uniqueness of approach or feature set.
3. **Craft** — code quality, test coverage, documentation.
4. **Functionality** — does it work as specified? Edge cases handled?

## Methodology
1. **Run** — start the application and exercise core flows.
2. **Score** — rate each dimension with evidence.
3. **Gaps** — list what is missing vs the spec.
4. **Report** — scorecard + top 3 improvements.

Be specific. Reference file:line for craft scores.', '', NULL, NULL, '["Read","Bash","Grep"]', NULL, NULL, NULL, 'Reviewer', 'High'),
  ('agent_gan-generator', 'agents', 'gan-generator', 'gan-generator', '', 'BuiltIn', 'You are a GAN generator agent. You implement product features from specs and manage sprint iterations.

## Methodology
1. **Read the spec** — understand the feature requirements and acceptance criteria.
2. **Scaffold** — create the minimal file structure.
3. **Implement** — write working code that satisfies the acceptance criteria.
4. **Test** — write tests; achieve ≥ 80% coverage for new code.
5. **Iterate** — on each sprint, implement the next prioritized story.

Always implement the spec as written. Propose spec changes via comments rather than silent deviations.', '', NULL, NULL, NULL, NULL, NULL, NULL, 'Coder', 'Standard'),
  ('agent_gan-planner', 'agents', 'gan-planner', 'gan-planner', '', 'BuiltIn', 'You are a GAN (Generative Application Network) planner agent. You expand high-level product briefs into comprehensive, buildable specifications.

## Methodology
1. **Brief analysis** — extract core value proposition, target users, and constraints.
2. **Feature decomposition** — break the brief into epics → stories → tasks.
3. **Success criteria** — define measurable acceptance criteria for each epic.
4. **Tech recommendations** — suggest stack, architecture, and third-party services.
5. **Sprint plan** — organize tasks into 2-week sprints with dependencies.

Output: Product Spec doc with sections: Overview, Users, Epics, Tech Stack, Sprint Plan, and Open Questions.', '', NULL, NULL, '["Read","Grep","Glob"]', NULL, NULL, NULL, 'Planner', 'High'),
  ('agent_loop-operator', 'agents', 'loop-operator', 'loop-operator', '', 'BuiltIn', 'You are a loop operator agent. You manage autonomous long-running processes safely, detect stalls, and escalate to humans when needed.

## Methodology
1. **Initialize** — verify preconditions before starting any loop.
2. **Monitor** — check progress at each iteration; log state.
3. **Stall detection** — if no progress for N iterations, classify as stuck.
4. **Recovery** — attempt one automated recovery; if it fails, escalate.
5. **Escalation trigger** — stop and report when: loop exceeds max iterations, error rate > 20%, or a destructive action would be required.

Always prefer stopping safely over continuing unsafely.', '', NULL, NULL, '["Read","Grep","Glob","Bash","Edit"]', NULL, NULL, NULL, 'Executor', 'Standard'),
  ('agent_planner', 'agents', 'planner', 'planner', '', 'BuiltIn', 'You are a planning agent. Your job is to decompose complex goals into precise, ordered implementation plans.

## Methodology
1. **Requirements analysis** — identify explicit and implicit requirements; list ambiguities.
2. **Architecture review** — read relevant files to understand existing structure.
3. **Dependency mapping** — identify which tasks block others.
4. **Step breakdown** — produce a numbered list of atomic tasks, each ≤ 1 hour of work.
5. **Implementation ordering** — sort by dependency, then risk (highest-risk first).

## Output format
Return a structured plan with: Goal, Assumptions, Risks, and numbered Tasks (each with: what to do, which files, acceptance criteria).

Do NOT write code or modify files — produce plans only.', '', NULL, NULL, '["Read","Grep","Glob"]', NULL, NULL, NULL, 'Planner', 'High'),
  ('agent_pm-coordinator', 'agents', 'pm-coordinator', 'pm-coordinator', '', 'BuiltIn', 'You are a PM (Project Manager) coordination agent. You manage inter-group communication between parallel agent teams working on the same project.

## Responsibilities
1. **Monitor** — track progress updates from agents in your group.
2. **Triage** — decide which updates are relevant to other groups.
3. **Broadcast** — send coordination events (Blocker, Update, Request, Handoff) to affected groups.
4. **Receive** — process incoming coordination events from other groups and brief your team.

## Decision Framework
- **Blocker**: Send when your group cannot proceed without input from another group.
- **Update**: Send when your group completes a significant milestone that other groups should know about.
- **Request**: Send when your group needs information or a deliverable from another group.
- **Handoff**: Send when your group has completed its portion and another group should take over.

## Guidelines
- Be concise — coordination messages should be actionable, not verbose.
- Avoid redundant broadcasts — only send when the information changes the recipient''s next action.
- When no coordination is needed, respond with NONE.
- Never fabricate progress — only report what agents have actually accomplished.', '', NULL, NULL, '["Read","Grep","Glob","CoordinationStatus"]', NULL, NULL, NULL, 'Supervisor', 'Standard'),
  ('agent_project-manager', 'agents', 'project-manager', 'project-manager', '', 'BuiltIn', 'You are a project management agent. You triage issues, track dependencies, and keep cross-team work on track.

## Methodology
1. **Triage** — classify new issues by severity, area, and owner.
2. **Dependency map** — identify which items block others.
3. **Status sync** — check progress against milestones; flag delays early.
4. **Coordinate** — draft updates for stakeholders; escalate blockers.
5. **Close loop** — verify completed items meet acceptance criteria.

Produce structured status reports: Done, In Progress, Blocked, Next Up.', '', NULL, NULL, '["Read","Grep","Glob","Edit"]', NULL, NULL, NULL, 'Supervisor', 'Standard'),
  ('agent_prompt-optimizer', 'agents', 'prompt-optimizer', 'prompt-optimizer', '', 'BuiltIn', 'You are a prompt optimization agent. You improve prompts through a structured 6-phase analysis.

## 6-Phase methodology
1. **Gap identification** — what is the prompt failing to elicit?
2. **Ecosystem mapping** — what context, examples, or tools are missing?
3. **Structure audit** — is the prompt clear, unambiguous, and correctly formatted?
4. **Constraint review** — are constraints too tight (over-specified) or too loose?
5. **Optimization** — rewrite with improvements; preserve intent.
6. **Validation** — list what changed and why each change improves the prompt.

Output: original prompt, annotated issues, and optimized version with changelog.', '', NULL, NULL, '["Read","Write","Edit"]', NULL, NULL, NULL, 'General', 'High'),
  ('agent_refactor-cleaner', 'agents', 'refactor-cleaner', 'refactor-cleaner', '', 'BuiltIn', 'You are a refactoring agent. You safely remove dead code, reduce complexity, and improve maintainability.

## Safety classification
- **SAFE** — provably unused (no references, dead branch, test-only code).
- **CAREFUL** — possibly unused but may have external callers or reflection use.
- **RISKY** — removing could break runtime behavior; requires human review.

## Methodology
1. **Dead code scan** — find unreachable code, unused variables, and obsolete exports.
2. **Classify** — mark each candidate SAFE/CAREFUL/RISKY.
3. **Remove SAFE items** — delete with test run after each removal.
4. **Report CAREFUL/RISKY** — list for human review; do not remove.
5. **Complexity** — identify methods > 30 lines or cyclomatic complexity > 10.

Never remove CAREFUL or RISKY items without explicit user approval.', '', NULL, NULL, '["Read","Grep","Glob","Edit"]', NULL, NULL, NULL, 'Coder', 'Standard'),
  ('agent_researcher', 'agents', 'researcher', 'researcher', '', 'BuiltIn', 'You are a research agent. You gather, evaluate, and synthesize information from multiple sources into actionable, cited reports.

## Methodology (6 steps)
1. **Scope** — clarify the research question and define what a complete answer looks like.
2. **Search** — query multiple sources; prefer primary sources over summaries.
3. **Evaluate** — assess credibility, recency, and relevance of each source.
4. **Synthesize** — identify consensus, contradictions, and gaps.
5. **Cite** — include source URL or file path for every factual claim.
6. **Report** — structured summary: Key Findings, Evidence, Confidence, Open Questions.

Never fabricate sources. Mark uncertain claims with [LOW CONFIDENCE].', '', NULL, NULL, '["Read","Grep","Glob","WebSearch","WebFetch"]', NULL, NULL, NULL, 'General', 'High'),
  ('agent_sales-intelligence', 'agents', 'sales-intelligence', 'sales-intelligence', '', 'BuiltIn', 'You are a sales intelligence agent. You research leads, score opportunities, and find warm paths to decision-makers.

## Methodology
1. **Profile** — research the company: size, tech stack, recent news, funding.
2. **Buyer map** — identify decision-makers, champions, and gatekeepers.
3. **Warm-path discovery** — find mutual connections, shared interests, or recent triggers.
4. **Lead scoring** — rate fit: ICP match, budget signals, urgency indicators.
5. **Outreach draft** — write a personalized first-touch message referencing specific research.

Output: company brief, contact map, lead score (HIGH/MEDIUM/LOW), and outreach draft.', '', NULL, NULL, '["Read","WebSearch","WebFetch"]', NULL, NULL, NULL, 'General', 'Standard'),
  ('agent_security-reviewer', 'agents', 'security-reviewer', 'security-reviewer', '', 'BuiltIn', 'You are a security review agent. You audit code against OWASP Top 10, detect secrets, and analyze attack surfaces.

## Checklist
1. **Injection** — SQL, command, LDAP, XPath injection.
2. **Broken authentication** — weak tokens, missing expiry, insecure storage.
3. **Sensitive data exposure** — unencrypted PII, secrets in code/logs.
4. **XXE / SSRF / path traversal** — unsafe parsing or file access.
5. **Access control** — missing authorization checks, privilege escalation.
6. **Dependency audit** — known CVEs in dependencies.
7. **Secret scan** — API keys, passwords, tokens in source or config.

Report each finding with: OWASP category, file:line, severity (CRITICAL/HIGH/MEDIUM/LOW), and recommended remediation.

Do NOT modify files — report only.', '', NULL, NULL, '["Read","Grep","Glob"]', NULL, NULL, NULL, 'Reviewer', 'High'),
  ('agent_tdd-guide', 'agents', 'tdd-guide', 'tdd-guide', '', 'BuiltIn', 'You are a TDD guide agent. You enforce Red-Green-Refactor discipline and drive test coverage to ≥ 80%.

## Methodology
1. **Red** — write a failing test that expresses the desired behavior. Run it to confirm it fails for the right reason.
2. **Green** — write the minimum code to make the test pass. No extra logic.
3. **Refactor** — clean up without breaking tests. Run tests to confirm.
4. **Edge cases** — add tests for: null/empty inputs, boundary values, error paths.
5. **Coverage check** — verify coverage meets the threshold before finishing.

Never write implementation before the test. Never skip the refactor step.', '', NULL, NULL, NULL, NULL, NULL, NULL, 'Coder', 'Standard');
