# One-shot generator: reads built-in skill + agent .md files and emits
# V035__seed_builtin_knowledge.sql (INSERT rows into knowledge_pages).
# Mirrors SkillParser / AgentTemplateRegistry.ParseTemplateFile semantics.
# Run once; the .sql is committed and the .md files are then deleted.

$ErrorActionPreference = 'Stop'
$repo = 'C:\Work\ANANT\Sovrant\sovrant'
$skillsDir = Join-Path $repo 'src\Sovrant.Tools\Skills\skills'
$agentsDir = Join-Path $repo 'src\Sovrant.Agents\agents'
$outFile  = Join-Path $repo 'src\Sovrant.Runtime\Storage\Migrations\V035__seed_builtin_knowledge.sql'

function Sql([string]$s) {
    if ($null -eq $s) { return 'NULL' }
    return "'" + ($s -replace "'", "''") + "'"
}

function SqlNullable([string]$s) {
    if ([string]::IsNullOrWhiteSpace($s)) { return 'NULL' }
    return Sql $s
}

# description is NOT NULL DEFAULT '' — never emit NULL for it.
function SqlText([string]$s) {
    if ($null -eq $s) { return "''" }
    return Sql $s
}

# Parse "[a, b, c]" or "a, b, c" -> JSON array string, or $null if empty.
function ParseListJson([string]$raw) {
    if ([string]::IsNullOrWhiteSpace($raw)) { return $null }
    $v = $raw.Trim()
    if ($v.StartsWith('[') -and $v.EndsWith(']')) { $v = $v.Substring(1, $v.Length - 2) }
    $items = $v.Split(',') | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' }
    if ($items.Count -eq 0) { return $null }
    $escaped = $items | ForEach-Object { '"' + ($_ -replace '\\', '\\' -replace '"', '\"') + '"' }
    return '[' + ($escaped -join ',') + ']'
}

# Split a .md file into (frontmatter-hashtable, body). Returns $null if no frontmatter.
function ParseFile([string]$path) {
    $text = [System.IO.File]::ReadAllText($path) -replace "`r`n", "`n"
    if (-not $text.StartsWith("---`n")) { return $null }
    $end = $text.IndexOf("`n---`n", 4)
    if ($end -lt 0) { return $null }
    $fm = $text.Substring(4, $end - 4)
    $body = $text.Substring($end + 5).Trim()
    $meta = @{}
    foreach ($line in $fm.Split("`n")) {
        $colon = $line.IndexOf(':')
        if ($colon -lt 0) { continue }
        $key = $line.Substring(0, $colon).Trim()
        $val = $line.Substring($colon + 1).Trim()
        $meta[$key] = $val
    }
    return @{ Meta = $meta; Body = $body }
}

$rows = New-Object System.Collections.Generic.List[string]

# ── Skills ──────────────────────────────────────────────────────────────
$skillFiles = Get-ChildItem -Path $skillsDir -Filter *.md | Sort-Object Name
foreach ($f in $skillFiles) {
    $p = ParseFile $f.FullName
    if ($null -eq $p) { Write-Warning "skip skill $($f.Name)"; continue }
    $slug = [System.IO.Path]::GetFileNameWithoutExtension($f.Name)
    $name = $p.Meta['name']; if ([string]::IsNullOrWhiteSpace($name)) { $name = $slug }
    $desc = $p.Meta['description']
    $trigger = $p.Meta['trigger']
    $agentsJson = ParseListJson $p.Meta['agents']
    $toolsJson  = ParseListJson $p.Meta['tools']
    $row = "  ('skill_$slug', 'skills', $(Sql $slug), $(Sql $name), $(SqlText $desc), 'BuiltIn', $(Sql $p.Body), '', " +
           "$(SqlNullable $trigger), $(if ($agentsJson) { Sql $agentsJson } else { 'NULL' }), $(if ($toolsJson) { Sql $toolsJson } else { 'NULL' }), " +
           "NULL, NULL, NULL, NULL, NULL)"
    $rows.Add($row)
}

# ── Agents ──────────────────────────────────────────────────────────────
$agentFiles = Get-ChildItem -Path $agentsDir -Filter *.md | Sort-Object Name
foreach ($f in $agentFiles) {
    $p = ParseFile $f.FullName
    if ($null -eq $p) { Write-Warning "skip agent $($f.Name)"; continue }
    $slug = [System.IO.Path]::GetFileNameWithoutExtension($f.Name)
    $name = $p.Meta['name']; if ([string]::IsNullOrWhiteSpace($name)) { $name = $slug }
    $desc = $p.Meta['description']
    $role = $p.Meta['role']
    $level = $p.Meta['recommended_level']
    $toolsJson = ParseListJson $p.Meta['allowed_tools']
    # columns: id, kind, slug, name, description, tier, body, workspace_id,
    #          trigger, agents, tools, industry, default_format, category, role, recommended_level
    $row = "  ('agent_$slug', 'agents', $(Sql $slug), $(Sql $name), $(SqlText $desc), 'BuiltIn', $(Sql $p.Body), '', " +
           "NULL, NULL, $(if ($toolsJson) { Sql $toolsJson } else { 'NULL' }), " +
           "NULL, NULL, NULL, $(SqlNullable $role), $(SqlNullable $level))"
    $rows.Add($row)
}

$header = @"
-- V035: Seed built-in knowledge (skills + agents) into knowledge_pages.
-- Phase 109. Generated from the former on-disk markdown by tools/gen-seed-knowledge.ps1.
-- These are the immutable factory rows (tier='BuiltIn', workspace_id=''); user edits
-- land in separate overlay rows ('global' / project) and are never clobbered here.
-- DO NOT edit this file in place after it ships; update built-in content via a new
-- additive Vxxx migration that UPDATEs the matching base row.
INSERT INTO knowledge_pages
    (knowledge_id, kind, slug, name, description, tier, body, workspace_id,
     trigger, agents, tools, industry, default_format, category, role, recommended_level)
VALUES
"@

$sql = $header + ($rows -join ",`n") + ";`n"
[System.IO.File]::WriteAllText($outFile, $sql, [System.Text.UTF8Encoding]::new($false))
Write-Output "Wrote $($rows.Count) rows to $outFile"
